/* ============================================================
   D&D 5E COMPREHENSIVE LOOT DATA
   Sources: DMG, XGtE, TCoE, MToF, VGtM, FToD, BoMT, SCAG,
            GGtR, EGtW, IDRotF, CoS, ToA, LMoP, SKT, HotDQ,
            PotA, OotA, RoT, DiA, GoS, BGDIA, CM, WDH, WDMM,
            KftGV, DoSI, SatO, VEoR, PAitM, HftT, LoX
   ============================================================ */

const lootData = {

  coins: {
    cp: { name: 'Copper Pieces',   icon: '🪙', value: 0.01 },
    sp: { name: 'Silver Pieces',   icon: '🥈', value: 0.1  },
    ep: { name: 'Electrum Pieces', icon: '⚡', value: 0.5  },
    gp: { name: 'Gold Pieces',     icon: '🥇', value: 1    },
    pp: { name: 'Platinum Pieces', icon: '💎', value: 10   }
  },

  gems: {
    '10': ['Azurite','Banded Agate','Blue Quartz','Eye Agate','Hematite','Lapis Lazuli','Malachite','Obsidian','Rhodochrosite','Tiger Eye Agate','Turquoise','Moss Agate','Snowflake Obsidian','Raw Amber (chip)','Polished Granite Sphere'],
    '50': ['Bloodstone','Carnelian','Chalcedony','Chrysoprase','Citrine','Jasper','Moonstone','Onyx','Peridot','Rock Crystal','Sard','Sardonyx','Smoky Quartz','Star Rose Quartz','Zircon','Aventurine','Iolite','Labradorite','Prehnite','Sunstone','Unakite'],
    '100': ['Amber','Amethyst','Chrysoberyl','Coral','Red Garnet','Jade','Jet','Freshwater Pearl','Red Spinel','Tourmaline','Fire Opal (small)','Heliodor','Kunzite','Morganite','Pink Tourmaline','Tsavorite Garnet'],
    '500': ['Alexandrite','Aquamarine','Black Pearl','Blue Spinel','Fire Opal','Topaz','Pink Pearl','Golden Beryl','Indicolite Tourmaline','Malaia Garnet','Oregon Sunstone','Padparadscha Sapphire'],
    '1000': ['Black Sapphire','Diamond','Jacinth','Ruby','Star Ruby','Star Sapphire (blue)','Fine Alexandrite','Large Tsavorite','Demantoid Garnet','Red Beryl'],
    '5000': ['Black Opal','Blue Diamond','Flawless Emerald','Flawless Ruby','Black Star Sapphire','Flawless Diamond','Imperial Jadeite','Paraiba Tourmaline','Red Diamond','Fancy Vivid Yellow Diamond']
  },

  art: {
    '25': ['Silver ewer','Carved bone statuette','Small gold bracelet','Cloth-of-gold vestments','Black velvet mask stitched with silver','Copper chalice with silver filigree','Pair of engraved bone dice','Small painted wooden mirror frame','Embroidered silk handkerchief','Gold locket with painted portrait','Silver dagger with jade pommel','Tarnished gold signet ring','Painted gold child\'s sarcophagus','Brass statuette of a war horse','Decorative silver inkpot','Carved obsidian cameo'],
    '250': ['Gold ring with bloodstones','Carved ivory statuette','Large gold bracelet','Silver necklace with gemstone pendant','Bronze crown','Silk robe with gold embroidery','Large well-made tapestry','Brass mug with jade inlay','Box of turquoise animal figurines','Gold birdcage with electrum filigree','Old masterwork painting in gilt frame','Carved jade idol','Silver altar piece with religious icons','Silver and gold hairnet with pearls','Painted wood shield with gold trim','Ceremonial dagger with ruby pommel'],
    '750': ['Silver chalice set with moonstones','Silver-plated longsword with jet set in hilt','Carved harp of exotic wood with ivory and zircon','Small gold idol','Gold dragon comb with garnet eyes','Bottle stopper cork embossed with gold and amethysts','Ceremonial electrum dagger with black pearl pommel','Silver and gold brooch','Obsidian statuette with gold fittings','Painted gold war mask','Black velvet mask set with citrines','Gold-inlaid obsidian mirror','Masterwork lute with intricate carvings','Jeweled gold crown (replica)','Adamantine medallion with dragon motif','Carved bone puzzle box with silver hinges'],
    '2500': ['Fine gold chain set with fire opal','Old masterpaintng on ivory','Embroidered silk and velvet mantle set with moonstones','Platinum bracelet set with sapphire','Jeweled anklet','Gold music box','Gold circlet set with four aquamarines','Eye patch with mock eye of blue sapphire and moonstone','String of small pink pearls','Jeweled gold crown','Jeweled platinum ring','Small gold statuette set with rubies','Gold cup set with emeralds','Gold jewelry box with platinum filigree','Enchanted portrait that watches observers','Bejeweled reliquary of an ancient saint'],
    '7500': ['Ancient jeweled gold crown','Legendary jeweled platinum ring','Small ancient gold idol set with rubies','Ornate golden scepter','Bejeweled platinum goblet','Emerald-studded battle crown','Diamond-encrusted shield boss','Sapphire-set golden torc','Ruby-crowned ivory staff','Platinum holy symbol set with diamonds','Golden orrery showing planetary positions','Mithral-inlaid chess set with jeweled pieces'],
    '25000': ['Legendary fine gold chain with fire opal','Jeweled platinum medallion of a lost empire','Ancient dragon skull with gold inlay','Dragon-scale mosaic on platinum backing','Crown of a fallen empire set with priceless gems','Divine relic of an ancient god','Adamantine statuette set with rare gems','Bejeweled draconic skull trophy','Ancient treaty document in solid gold frame','Legendary bard\'s lute studded with stars of diamonds']
  },

  magicItems: {
    common: [
      {name:'Potion of Climbing',type:'potion',attune:false},
      {name:'Potion of Healing',type:'potion',attune:false},
      {name:'Spell Scroll (Cantrip)',type:'scroll',attune:false},
      {name:'Spell Scroll (1st Level)',type:'scroll',attune:false},
      {name:'Wand of Smiles',type:'wand',attune:false},
      {name:'Wand of Scowls',type:'wand',attune:false},
      {name:'Hat of Vermin',type:'wondrous',attune:false},
      {name:'Hat of Wizardry',type:'wondrous',attune:true},
      {name:'Cloak of Billowing',type:'wondrous',attune:false},
      {name:'Cloak of Many Fashions',type:'wondrous',attune:false},
      {name:'Ear Horn of Hearing',type:'wondrous',attune:false},
      {name:'Orb of Direction',type:'wondrous',attune:false},
      {name:'Orb of Time',type:'wondrous',attune:false},
      {name:'Pipe of Smoke Monsters',type:'wondrous',attune:false},
      {name:'Pole of Angling',type:'wondrous',attune:false},
      {name:'Pole of Collapsing',type:'wondrous',attune:false},
      {name:'Pot of Awakening',type:'wondrous',attune:false},
      {name:'Ruby of the War Mage',type:'wondrous',attune:true},
      {name:'Shield of Expression',type:'armor',attune:false},
      {name:'Smoldering Armor',type:'armor',attune:false},
      {name:'Staff of Adornment',type:'staff',attune:false},
      {name:'Staff of Birdcalls',type:'staff',attune:false},
      {name:'Staff of Flowers',type:'staff',attune:false},
      {name:'Talking Doll',type:'wondrous',attune:true},
      {name:"Veteran's Cane",type:'wondrous',attune:false},
      {name:'Walloping Ammunition',type:'weapon',attune:false},
      {name:'Mystery Key',type:'wondrous',attune:false},
      {name:'Instrument of Illusions',type:'wondrous',attune:true},
      {name:'Perfume of Bewitching',type:'wondrous',attune:false},
      {name:'Potion of Comprehension',type:'potion',attune:false},
      {name:'Prosthetic Limb',type:'wondrous',attune:false},
      {name:'Pipe of Remembrance',type:'wondrous',attune:false},
      {name:"Heward's Handy Spice Pouch",type:'wondrous',attune:false},
      {name:"Charlatan's Die",type:'wondrous',attune:true},
      {name:'Dread Helm',type:'wondrous',attune:false},
      {name:'Enduring Spellbook',type:'wondrous',attune:false},
      {name:'Moon-Touched Sword',type:'weapon',attune:false},
      {name:'Rope of Mending',type:'wondrous',attune:false},
      {name:'Candle of the Deep',type:'wondrous',attune:false},
      {name:'Ersatz Eye',type:'wondrous',attune:true},
      {name:'Imbued Wood Focus',type:'wondrous',attune:true},
      {name:'Masquerade Tattoo',type:'wondrous',attune:true},
      {name:'Silvered Weapon',type:'weapon',attune:false},
    ],
    uncommon: [
      {name:'+1 Weapon',type:'weapon',attune:false},
      {name:'+1 Shield',type:'armor',attune:false},
      {name:'+1 Ammunition (20)',type:'weapon',attune:false},
      {name:'Adamantine Armor',type:'armor',attune:false},
      {name:'Alchemy Jug',type:'wondrous',attune:false},
      {name:'Ammunition of Slaying',type:'weapon',attune:false},
      {name:'Amulet of Proof Against Detection',type:'wondrous',attune:true},
      {name:'Bag of Holding',type:'wondrous',attune:false},
      {name:'Bag of Tricks (Gray)',type:'wondrous',attune:false},
      {name:'Bag of Tricks (Rust)',type:'wondrous',attune:false},
      {name:'Bag of Tricks (Tan)',type:'wondrous',attune:false},
      {name:'Boots of Elvenkind',type:'wondrous',attune:false},
      {name:'Boots of Striding and Springing',type:'wondrous',attune:true},
      {name:'Boots of the Winterlands',type:'wondrous',attune:true},
      {name:'Bracers of Archery',type:'wondrous',attune:true},
      {name:'Brooch of Shielding',type:'wondrous',attune:true},
      {name:'Broom of Flying',type:'wondrous',attune:false},
      {name:'Cap of Water Breathing',type:'wondrous',attune:false},
      {name:'Circlet of Blasting',type:'wondrous',attune:false},
      {name:'Cloak of Elvenkind',type:'wondrous',attune:true},
      {name:'Cloak of Protection',type:'wondrous',attune:true},
      {name:'Cloak of the Manta Ray',type:'wondrous',attune:false},
      {name:'Deck of Illusions',type:'wondrous',attune:false},
      {name:'Decanter of Endless Water',type:'wondrous',attune:false},
      {name:'Driftglobe',type:'wondrous',attune:false},
      {name:'Dust of Disappearance',type:'wondrous',attune:false},
      {name:'Dust of Dryness',type:'wondrous',attune:false},
      {name:'Dust of Sneezing and Choking',type:'wondrous',attune:false},
      {name:'Elemental Gem',type:'wondrous',attune:false},
      {name:'Eversmoking Bottle',type:'wondrous',attune:false},
      {name:'Eyes of Charming',type:'wondrous',attune:true},
      {name:'Eyes of Minute Seeing',type:'wondrous',attune:false},
      {name:'Eyes of the Eagle',type:'wondrous',attune:true},
      {name:'Figurine of Wondrous Power (Silver Raven)',type:'wondrous',attune:false},
      {name:'Folding Boat',type:'wondrous',attune:false},
      {name:'Gauntlets of Ogre Power',type:'wondrous',attune:true},
      {name:'Gem of Brightness',type:'wondrous',attune:false},
      {name:'Gloves of Missile Snaring',type:'wondrous',attune:true},
      {name:'Gloves of Swimming and Climbing',type:'wondrous',attune:true},
      {name:'Gloves of Thievery',type:'wondrous',attune:false},
      {name:'Goggles of Night',type:'wondrous',attune:false},
      {name:'Hat of Disguise',type:'wondrous',attune:true},
      {name:'Headband of Intellect',type:'wondrous',attune:true},
      {name:'Helm of Comprehending Languages',type:'wondrous',attune:false},
      {name:'Helm of Telepathy',type:'wondrous',attune:true},
      {name:'Horseshoes of Speed',type:'wondrous',attune:false},
      {name:'Immovable Rod',type:'rod',attune:false},
      {name:"Instrument of the Bards (Doss Lute)",type:'wondrous',attune:true},
      {name:"Instrument of the Bards (Fochlucan Bandore)",type:'wondrous',attune:true},
      {name:"Instrument of the Bards (Mac-Fuirmidh Cittern)",type:'wondrous',attune:true},
      {name:'Javelin of Lightning',type:'weapon',attune:false},
      {name:'Lantern of Revealing',type:'wondrous',attune:false},
      {name:'Medallion of Thoughts',type:'wondrous',attune:true},
      {name:'Mithral Armor',type:'armor',attune:false},
      {name:'Necklace of Adaptation',type:'wondrous',attune:true},
      {name:'Pearl of Power',type:'wondrous',attune:true},
      {name:'Periapt of Health',type:'wondrous',attune:false},
      {name:'Periapt of Wound Closure',type:'wondrous',attune:true},
      {name:'Philter of Love',type:'potion',attune:false},
      {name:'Pipes of Haunting',type:'wondrous',attune:false},
      {name:'Pipes of the Sewers',type:'wondrous',attune:true},
      {name:'Potion of Animal Friendship',type:'potion',attune:false},
      {name:'Potion of Fire Breath',type:'potion',attune:false},
      {name:'Potion of Giant Strength (Hill)',type:'potion',attune:false},
      {name:'Potion of Greater Healing',type:'potion',attune:false},
      {name:'Potion of Growth',type:'potion',attune:false},
      {name:'Potion of Heroism',type:'potion',attune:false},
      {name:'Potion of Invisibility',type:'potion',attune:false},
      {name:'Potion of Mind Reading',type:'potion',attune:false},
      {name:'Potion of Poison',type:'potion',attune:false},
      {name:'Potion of Resistance',type:'potion',attune:false},
      {name:'Potion of Water Breathing',type:'potion',attune:false},
      {name:'Quiver of Ehlonna',type:'wondrous',attune:false},
      {name:'Ring of Jumping',type:'ring',attune:true},
      {name:'Ring of Mind Shielding',type:'ring',attune:true},
      {name:'Ring of Swimming',type:'ring',attune:false},
      {name:'Ring of Warmth',type:'ring',attune:true},
      {name:'Ring of Water Walking',type:'ring',attune:false},
      {name:'Robe of Useful Items',type:'wondrous',attune:false},
      {name:'Rod of the Pact Keeper +1',type:'rod',attune:true},
      {name:'Rope of Climbing',type:'wondrous',attune:false},
      {name:'Saddle of the Cavalier',type:'wondrous',attune:false},
      {name:'Sending Stones',type:'wondrous',attune:false},
      {name:'Slippers of Spider Climbing',type:'wondrous',attune:true},
      {name:'Spell Scroll (2nd Level)',type:'scroll',attune:false},
      {name:'Spell Scroll (3rd Level)',type:'scroll',attune:false},
      {name:'Staff of the Adder',type:'staff',attune:true},
      {name:'Staff of the Python',type:'staff',attune:true},
      {name:'Stone of Good Luck',type:'wondrous',attune:true},
      {name:'Sword of Vengeance',type:'weapon',attune:true},
      {name:'Trident of Fish Command',type:'weapon',attune:true},
      {name:'Wand of Magic Detection',type:'wand',attune:false},
      {name:'Wand of Magic Missiles',type:'wand',attune:false},
      {name:'Wand of Secrets',type:'wand',attune:false},
      {name:'Wand of the War Mage +1',type:'wand',attune:true},
      {name:'Wand of Web',type:'wand',attune:true},
      {name:'Wind Fan',type:'wondrous',attune:false},
      {name:'Winged Boots',type:'wondrous',attune:true},
      // TCoE
      {name:'All-Purpose Tool +1',type:'wondrous',attune:true},
      {name:'Amulet of the Devout +1',type:'wondrous',attune:true},
      {name:'Arcane Grimoire +1',type:'wondrous',attune:true},
      {name:'Bloodwell Vial +1',type:'wondrous',attune:true},
      {name:'Guardian Emblem',type:'wondrous',attune:true},
      {name:"Illuminator's Tattoo",type:'wondrous',attune:true},
      {name:'Keen Mind Tattoo',type:'wondrous',attune:true},
      {name:'Shadowfell Brand Tattoo',type:'wondrous',attune:true},
      {name:'Spellwrought Tattoo (1st)',type:'wondrous',attune:false},
      {name:'Spellwrought Tattoo (2nd)',type:'wondrous',attune:false},
      {name:'Coiling Grasp Tattoo',type:'wondrous',attune:true},
      {name:'Feywild Shard',type:'wondrous',attune:true},
      {name:'Moon Sickle +1',type:'weapon',attune:true},
      {name:"Rhythm-Maker's Drum +1",type:'wondrous',attune:true},
      {name:"Nature's Mantle",type:'wondrous',attune:true},
      {name:'Astral Shard',type:'wondrous',attune:true},
      {name:'Bell Branch',type:'wondrous',attune:true},
      {name:'Lyre of Building',type:'wondrous',attune:true},
      {name:'Outer Essence Shard',type:'wondrous',attune:true},
      {name:'Wheel of Stars',type:'wondrous',attune:true},
      {name:"Devotee's Censer",type:'wondrous',attune:true},
      {name:'Helm of Awareness',type:'wondrous',attune:true},
    ],
    rare: [
      {name:'+2 Weapon',type:'weapon',attune:false},
      {name:'+2 Shield',type:'armor',attune:false},
      {name:'+1 Armor',type:'armor',attune:true},
      {name:'Amulet of Health',type:'wondrous',attune:true},
      {name:'Animated Shield',type:'armor',attune:true},
      {name:'Apparatus of Kwalish',type:'wondrous',attune:false},
      {name:'Armor of Resistance',type:'armor',attune:true},
      {name:'Arrow-Catching Shield',type:'armor',attune:true},
      {name:'Bag of Beans',type:'wondrous',attune:false},
      {name:'Bead of Force',type:'wondrous',attune:false},
      {name:'Belt of Dwarvenkind',type:'wondrous',attune:true},
      {name:'Belt of Giant Strength (Hill)',type:'wondrous',attune:true},
      {name:'Berserker Axe',type:'weapon',attune:true},
      {name:'Boots of Levitation',type:'wondrous',attune:true},
      {name:'Boots of Speed',type:'wondrous',attune:true},
      {name:'Bowl of Commanding Water Elementals',type:'wondrous',attune:false},
      {name:'Bracers of Defense',type:'wondrous',attune:true},
      {name:'Brazier of Commanding Fire Elementals',type:'wondrous',attune:false},
      {name:'Cape of the Mountebank',type:'wondrous',attune:false},
      {name:'Censer of Controlling Air Elementals',type:'wondrous',attune:false},
      {name:'Chime of Opening',type:'wondrous',attune:false},
      {name:'Cloak of Displacement',type:'wondrous',attune:true},
      {name:'Cloak of the Bat',type:'wondrous',attune:true},
      {name:'Cube of Force',type:'wondrous',attune:true},
      {name:"Daern's Instant Fortress",type:'wondrous',attune:false},
      {name:'Dagger of Venom',type:'weapon',attune:false},
      {name:'Dancing Sword',type:'weapon',attune:true},
      {name:'Demon Armor',type:'armor',attune:true},
      {name:'Dragon Scale Mail',type:'armor',attune:true},
      {name:'Dragon Slayer',type:'weapon',attune:false},
      {name:'Dwarven Plate',type:'armor',attune:false},
      {name:'Dwarven Thrower',type:'weapon',attune:true},
      {name:'Efreeti Bottle',type:'wondrous',attune:false},
      {name:'Elven Chain',type:'armor',attune:false},
      {name:'Figurine of Wondrous Power (Bronze Griffon)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Ebony Fly)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Golden Lions)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Ivory Goats)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Marble Elephant)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Onyx Dog)',type:'wondrous',attune:false},
      {name:'Figurine of Wondrous Power (Serpentine Owl)',type:'wondrous',attune:false},
      {name:'Flame Tongue',type:'weapon',attune:true},
      {name:'Frost Brand',type:'weapon',attune:true},
      {name:'Gem of Seeing',type:'wondrous',attune:true},
      {name:'Giant Slayer',type:'weapon',attune:false},
      {name:'Glamoured Studded Leather',type:'armor',attune:false},
      {name:'Hammer of Thunderbolts',type:'weapon',attune:false},
      {name:'Handy Haversack',type:'wondrous',attune:false},
      {name:'Ioun Stone (Awareness)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Protection)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Reserve)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Sustenance)',type:'wondrous',attune:true},
      {name:'Iron Bands of Bilarro',type:'wondrous',attune:false},
      {name:'Mace of Disruption',type:'weapon',attune:true},
      {name:'Mace of Smiting',type:'weapon',attune:false},
      {name:'Mace of Terror',type:'weapon',attune:true},
      {name:'Mantle of Spell Resistance',type:'wondrous',attune:true},
      {name:'Necklace of Fireballs',type:'wondrous',attune:false},
      {name:'Necklace of Prayer Beads',type:'wondrous',attune:true},
      {name:'Oathbow',type:'weapon',attune:true},
      {name:'Oil of Slipperiness',type:'potion',attune:false},
      {name:'Periapt of Proof Against Poison',type:'wondrous',attune:false},
      {name:'Portable Hole',type:'wondrous',attune:false},
      {name:'Potion of Clairvoyance',type:'potion',attune:false},
      {name:'Potion of Diminution',type:'potion',attune:false},
      {name:'Potion of Gaseous Form',type:'potion',attune:false},
      {name:'Potion of Giant Strength (Frost)',type:'potion',attune:false},
      {name:'Potion of Giant Strength (Stone)',type:'potion',attune:false},
      {name:'Potion of Superior Healing',type:'potion',attune:false},
      {name:'Potion of Invulnerability',type:'potion',attune:false},
      {name:'Ring of Animal Influence',type:'ring',attune:false},
      {name:'Ring of Evasion',type:'ring',attune:true},
      {name:'Ring of Feather Falling',type:'ring',attune:true},
      {name:'Ring of Free Action',type:'ring',attune:true},
      {name:'Ring of Protection',type:'ring',attune:true},
      {name:'Ring of Resistance',type:'ring',attune:true},
      {name:'Ring of Spell Storing',type:'ring',attune:true},
      {name:'Ring of the Ram',type:'ring',attune:true},
      {name:'Ring of X-Ray Vision',type:'ring',attune:true},
      {name:'Robe of Eyes',type:'wondrous',attune:true},
      {name:'Rod of Rulership',type:'rod',attune:true},
      {name:'Rod of the Pact Keeper +2',type:'rod',attune:true},
      {name:'Rope of Entanglement',type:'wondrous',attune:false},
      {name:'Scroll of Protection',type:'scroll',attune:false},
      {name:'Sentinel Shield',type:'armor',attune:false},
      {name:'Spell Scroll (4th Level)',type:'scroll',attune:false},
      {name:'Spell Scroll (5th Level)',type:'scroll',attune:false},
      {name:'Staff of Charming',type:'staff',attune:true},
      {name:'Staff of Healing',type:'staff',attune:true},
      {name:'Staff of Swarming Insects',type:'staff',attune:true},
      {name:'Staff of the Woodlands',type:'staff',attune:true},
      {name:'Staff of Withering',type:'staff',attune:true},
      {name:'Stone of Controlling Earth Elementals',type:'wondrous',attune:false},
      {name:'Sun Blade',type:'weapon',attune:true},
      {name:'Sword of Life Stealing',type:'weapon',attune:true},
      {name:'Sword of Wounding',type:'weapon',attune:true},
      {name:'Tentacle Rod',type:'rod',attune:true},
      {name:'Wand of Binding',type:'wand',attune:true},
      {name:'Wand of Enemy Detection',type:'wand',attune:true},
      {name:'Wand of Fear',type:'wand',attune:true},
      {name:'Wand of Fireballs',type:'wand',attune:true},
      {name:'Wand of Lightning Bolts',type:'wand',attune:true},
      {name:'Wand of Paralysis',type:'wand',attune:true},
      {name:'Wand of the War Mage +2',type:'wand',attune:true},
      {name:'Wand of Wonder',type:'wand',attune:true},
      {name:'Wings of Flying',type:'wondrous',attune:true},
      // TCoE / XGtE
      {name:'Absorbing Tattoo',type:'wondrous',attune:true},
      {name:'All-Purpose Tool +2',type:'wondrous',attune:true},
      {name:'Amulet of the Devout +2',type:'wondrous',attune:true},
      {name:'Arcane Grimoire +2',type:'wondrous',attune:true},
      {name:'Barrier Tattoo (Medium)',type:'wondrous',attune:true},
      {name:'Bloodwell Vial +2',type:'wondrous',attune:true},
      {name:'Ghost Step Tattoo',type:'wondrous',attune:true},
      {name:'Moon Sickle +2',type:'weapon',attune:true},
      {name:"Rhythm-Maker's Drum +2",type:'wondrous',attune:true},
      {name:'Spellwrought Tattoo (3rd)',type:'wondrous',attune:false},
      {name:'Spellwrought Tattoo (4th)',type:'wondrous',attune:false},
      {name:"Instrument of the Bards (Cli Lyre)",type:'wondrous',attune:true},
      {name:"Instrument of the Bards (Canaith Mandolin)",type:'wondrous',attune:true},
      {name:'Ioun Stone (Agility)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Fortitude)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Insight)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Intellect)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Leadership)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Strength)',type:'wondrous',attune:true},
      // Adventure books
      {name:'Ghost Lantern',type:'wondrous',attune:true},
      {name:'Icon of Ravenloft',type:'wondrous',attune:true},
      {name:'Orb of the Veil',type:'wondrous',attune:true},
      {name:'Ruby Weave Gem',type:'wondrous',attune:true},
      {name:'Shard of the Ise Rune',type:'wondrous',attune:false},
      {name:'Topaz Annihilator',type:'weapon',attune:true},
      {name:"Devotee's Censer (rare)",type:'wondrous',attune:true},
    ],
    'very-rare': [
      {name:'+3 Weapon',type:'weapon',attune:false},
      {name:'+2 Armor',type:'armor',attune:true},
      {name:'Amulet of the Planes',type:'wondrous',attune:true},
      {name:'Armor of Invulnerability',type:'armor',attune:true},
      {name:'Arrow of Slaying',type:'weapon',attune:false},
      {name:'Belt of Giant Strength (Fire)',type:'wondrous',attune:true},
      {name:'Belt of Giant Strength (Frost)',type:'wondrous',attune:true},
      {name:'Belt of Giant Strength (Stone)',type:'wondrous',attune:true},
      {name:'Candle of Invocation',type:'wondrous',attune:true},
      {name:'Carpet of Flying',type:'wondrous',attune:false},
      {name:'Cloak of Arachnida',type:'wondrous',attune:true},
      {name:'Crystal Ball (Standard)',type:'wondrous',attune:true},
      {name:'Crystal Ball of Mind Reading',type:'wondrous',attune:true},
      {name:'Crystal Ball of Telepathy',type:'wondrous',attune:true},
      {name:'Figurine of Wondrous Power (Obsidian Steed)',type:'wondrous',attune:false},
      {name:'Helm of Brilliance',type:'wondrous',attune:true},
      {name:'Holy Avenger',type:'weapon',attune:true},
      {name:'Horn of Valhalla (Bronze)',type:'wondrous',attune:false},
      {name:'Horn of Valhalla (Iron)',type:'wondrous',attune:false},
      {name:"Instrument of the Bards (Anstruth Harp)",type:'wondrous',attune:true},
      {name:'Ioun Stone (Absorption)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Mastery)',type:'wondrous',attune:true},
      {name:'Iron Flask',type:'wondrous',attune:false},
      {name:'Manual of Bodily Health',type:'wondrous',attune:false},
      {name:'Manual of Gainful Exercise',type:'wondrous',attune:false},
      {name:'Manual of Golems',type:'wondrous',attune:false},
      {name:'Manual of Quickness of Action',type:'wondrous',attune:false},
      {name:'Mirror of Life Trapping',type:'wondrous',attune:false},
      {name:'Nine Lives Stealer',type:'weapon',attune:true},
      {name:'Potion of Flying',type:'potion',attune:false},
      {name:'Potion of Giant Strength (Cloud)',type:'potion',attune:false},
      {name:'Potion of Giant Strength (Storm)',type:'potion',attune:false},
      {name:'Potion of Supreme Healing',type:'potion',attune:false},
      {name:'Ring of Regeneration',type:'ring',attune:true},
      {name:'Ring of Shooting Stars',type:'ring',attune:true},
      {name:'Ring of Telekinesis',type:'ring',attune:true},
      {name:'Robe of Scintillating Colors',type:'wondrous',attune:true},
      {name:'Robe of Stars',type:'wondrous',attune:true},
      {name:'Rod of Absorption',type:'rod',attune:true},
      {name:'Rod of Alertness',type:'rod',attune:true},
      {name:'Rod of Security',type:'rod',attune:false},
      {name:'Rod of the Pact Keeper +3',type:'rod',attune:true},
      {name:'Scimitar of Speed',type:'weapon',attune:true},
      {name:'Spell Scroll (6th Level)',type:'scroll',attune:false},
      {name:'Spell Scroll (7th Level)',type:'scroll',attune:false},
      {name:'Spell Scroll (8th Level)',type:'scroll',attune:false},
      {name:'Spellguard Shield',type:'armor',attune:true},
      {name:'Staff of Fire',type:'staff',attune:true},
      {name:'Staff of Frost',type:'staff',attune:true},
      {name:'Staff of Power',type:'staff',attune:true},
      {name:'Staff of Striking',type:'staff',attune:true},
      {name:'Staff of Thunder and Lightning',type:'staff',attune:true},
      {name:'Sword of Sharpness',type:'weapon',attune:true},
      {name:'Tome of Clear Thought',type:'wondrous',attune:false},
      {name:'Tome of Leadership and Influence',type:'wondrous',attune:false},
      {name:'Tome of Understanding',type:'wondrous',attune:false},
      {name:'Wand of Polymorph',type:'wand',attune:true},
      {name:'Wand of the War Mage +3',type:'wand',attune:true},
      // TCoE / XGtE
      {name:'All-Purpose Tool +3',type:'wondrous',attune:true},
      {name:'Amulet of the Devout +3',type:'wondrous',attune:true},
      {name:'Arcane Grimoire +3',type:'wondrous',attune:true},
      {name:'Barrier Tattoo (Heavy)',type:'wondrous',attune:true},
      {name:'Bloodwell Vial +3',type:'wondrous',attune:true},
      {name:'Moon Sickle +3',type:'weapon',attune:true},
      {name:"Rhythm-Maker's Drum +3",type:'wondrous',attune:true},
      {name:'Spellwrought Tattoo (5th)',type:'wondrous',attune:false},
      // Adventure / Setting
      {name:'Acheron Blade',type:'weapon',attune:true},
      {name:'Grimoire Infinitus',type:'wondrous',attune:true},
      {name:"Infiltrator's Key",type:'wondrous',attune:true},
      {name:'Lash of Shadows',type:'weapon',attune:true},
      {name:'Molten Bronze Skin',type:'armor',attune:true},
      {name:'Obsidian Flint Dragon Plate',type:'armor',attune:true},
      {name:'Potion of Giant Size',type:'potion',attune:false},
      {name:'Ruinous Flail',type:'weapon',attune:true},
      {name:'Spider Staff',type:'staff',attune:true},
      {name:'Staff of the Ivory Claw',type:'staff',attune:true},
      {name:'Waythe (Greatsword)',type:'weapon',attune:true},
      {name:'Battering Shield',type:'armor',attune:true},
    ],
    legendary: [
      {name:'+3 Armor',type:'armor',attune:true},
      {name:'Amulet of the Planes',type:'wondrous',attune:true},
      {name:'Armor of Invulnerability',type:'armor',attune:true},
      {name:'Belt of Giant Strength (Storm)',type:'wondrous',attune:true},
      {name:'Cloak of Invisibility',type:'wondrous',attune:true},
      {name:'Crystal Ball of True Seeing',type:'wondrous',attune:true},
      {name:'Cubic Gate',type:'wondrous',attune:false},
      {name:'Deck of Many Things',type:'wondrous',attune:false},
      {name:'Defender',type:'weapon',attune:true},
      {name:'Efreeti Chain',type:'armor',attune:true},
      {name:'Figurine of Wondrous Power (Diamond Spider)',type:'wondrous',attune:false},
      {name:'Helm of Teleportation',type:'wondrous',attune:true},
      {name:'Holy Avenger',type:'weapon',attune:true},
      {name:'Horn of Valhalla (Silver)',type:'wondrous',attune:false},
      {name:"Instrument of the Bards (Ollamh Harp)",type:'wondrous',attune:true},
      {name:'Ioun Stone (Greater Absorption)',type:'wondrous',attune:true},
      {name:'Ioun Stone (Regeneration)',type:'wondrous',attune:true},
      {name:'Luck Blade',type:'weapon',attune:true},
      {name:'Moonblade',type:'weapon',attune:true},
      {name:'Plate Armor of Etherealness',type:'armor',attune:true},
      {name:'Ring of Djinni Summoning',type:'ring',attune:true},
      {name:'Ring of Elemental Command (Air)',type:'ring',attune:true},
      {name:'Ring of Elemental Command (Earth)',type:'ring',attune:true},
      {name:'Ring of Elemental Command (Fire)',type:'ring',attune:true},
      {name:'Ring of Elemental Command (Water)',type:'ring',attune:true},
      {name:'Ring of Invisibility',type:'ring',attune:true},
      {name:'Ring of Spell Turning',type:'ring',attune:true},
      {name:'Ring of Three Wishes',type:'ring',attune:false},
      {name:'Robe of the Archmagi',type:'wondrous',attune:true},
      {name:'Rod of Lordly Might',type:'rod',attune:true},
      {name:'Rod of Resurrection',type:'rod',attune:true},
      {name:'Scarab of Protection',type:'wondrous',attune:true},
      {name:'Sovereign Glue',type:'wondrous',attune:false},
      {name:'Sphere of Annihilation',type:'wondrous',attune:false},
      {name:'Spell Scroll (9th Level)',type:'scroll',attune:false},
      {name:'Staff of the Magi',type:'staff',attune:true},
      {name:'Sword of Answering',type:'weapon',attune:true},
      {name:'Talisman of Pure Good',type:'wondrous',attune:true},
      {name:'Talisman of the Sphere',type:'wondrous',attune:true},
      {name:'Talisman of Ultimate Evil',type:'wondrous',attune:true},
      {name:'Tome of the Stilled Tongue',type:'wondrous',attune:true},
      {name:'Universal Solvent',type:'wondrous',attune:false},
      {name:'Vorpal Sword',type:'weapon',attune:true},
      {name:'Well of Many Worlds',type:'wondrous',attune:false},
      // TCoE / EGtW / Setting
      {name:'Blood Fury Tattoo',type:'wondrous',attune:true},
      {name:'Demonomicon of Iggwilv',type:'wondrous',attune:true},
      {name:'Flail of Tiamat',type:'weapon',attune:true},
      {name:'Gavel of the Venn Rune',type:'weapon',attune:false},
      {name:'Hide of the Feral Guardian',type:'armor',attune:true},
      {name:"Hunter's Coat",type:'armor',attune:true},
      {name:"Infernal Machine of Lum the Mad",type:'wondrous',attune:false},
      {name:'Matalotok (Frost Giant Hammer)',type:'weapon',attune:true},
      {name:'Orrery of the Wanderer',type:'wondrous',attune:true},
      {name:'Rod of the Vonindod',type:'rod',attune:false},
      {name:'Ruidium Armor',type:'armor',attune:true},
      {name:'Ruidium Weapon',type:'weapon',attune:true},
      {name:'Shield of the Hidden Lord',type:'armor',attune:true},
      {name:'Sword of Kas',type:'weapon',attune:true},
      {name:'Teeth of Dahlver-Nar',type:'wondrous',attune:false},
      {name:'Wand of Orcus',type:'wand',attune:true},
      {name:'Wave (Trident)',type:'weapon',attune:true},
      {name:'Whelm (Warhammer)',type:'weapon',attune:true},
      {name:'Blackrazor',type:'weapon',attune:true},
      {name:'Deck of Many Things (abridged)',type:'wondrous',attune:false},
    ],
    artifact: [
      {name:'Axe of the Dwarvish Lords',type:'weapon',attune:true},
      {name:'Book of Exalted Deeds',type:'wondrous',attune:true},
      {name:'Book of Vile Darkness',type:'wondrous',attune:true},
      {name:'Eye of Vecna',type:'wondrous',attune:true},
      {name:'Hand of Vecna',type:'wondrous',attune:true},
      {name:'Orb of Dragonkind',type:'wondrous',attune:true},
      {name:'Sword of Kas',type:'weapon',attune:true},
      {name:'Wand of Orcus',type:'wand',attune:true},
      {name:'Codex of Infinite Planes',type:'wondrous',attune:true},
      {name:'Crook of Rao',type:'wondrous',attune:true},
      {name:'Demonomicon of Iggwilv',type:'wondrous',attune:true},
      {name:'Mighty Servant of Leuk-o',type:'wondrous',attune:true},
      {name:'Teeth of Dahlver-Nar',type:'wondrous',attune:false},
      {name:"Baba Yaga's Mortar and Pestle",type:'wondrous',attune:true},
      {name:'Blackstaff (Waterdeep)',type:'staff',attune:true},
      {name:"Danoth's Visor",type:'wondrous',attune:true},
      {name:'Grovelthrash (Flail)',type:'weapon',attune:true},
      {name:'Jewel of Three Prayers',type:'wondrous',attune:true},
      {name:'Orrery of the Wanderer',type:'wondrous',attune:true},
      {name:"Ruin's Wake (Spear)",type:'weapon',attune:true},
      {name:'Spear of Backbiting',type:'weapon',attune:true},
    ]
  },

  // Magic item table mapping (DMG tables A-I → rarity pools)
  magicTables: {
    A: 'common',
    B: 'uncommon',
    C: 'uncommon',
    D: 'rare',
    E: 'rare',
    F: 'uncommon',
    G: 'rare',
    H: 'very-rare',
    I: 'legendary'
  },

  // DMG Treasure Tables (simplified but faithful)
  treasureTables: {
    individual: {
      '0-4':  { cp:[5,30],  sp:[2,12],  ep:0,       gp:[1,6],   pp:0,       gemChance:30, gemTier:'10',   artChance:0,  artTier:'25',   magicChance:0,  magicTable:'A' },
      '5-10': { cp:[4,24],  sp:[6,36],  ep:0,       gp:[2,12],  pp:0,       gemChance:40, gemTier:'50',   artChance:25, artTier:'25',   magicChance:15, magicTable:'B' },
      '11-16':{ cp:0,       sp:[4,24],  ep:[2,12],  gp:[2,12],  pp:[1,6],   gemChance:50, gemTier:'100',  artChance:40, artTier:'250',  magicChance:30, magicTable:'D' },
      '17+':  { cp:0,       sp:0,       ep:[2,12],  gp:[6,36],  pp:[2,12],  gemChance:60, gemTier:'500',  artChance:50, artTier:'2500', magicChance:50, magicTable:'H' }
    },
    hoard: {
      '0-4':  { cp:[6,36],  sp:[3,18],  ep:0,       gp:[2,12],  pp:0,       cpMult:100, spMult:100, gpMult:10,   gemChance:40, gemTier:'10',   artChance:30, artTier:'25',   magicChance:20, magicTable:'A', magicCount:[1,3] },
      '5-10': { cp:[2,12],  sp:[2,12],  ep:0,       gp:[6,36],  pp:[3,18],  cpMult:100, spMult:1000,gpMult:100,  gemChance:50, gemTier:'50',   artChance:40, artTier:'250',  magicChance:35, magicTable:'C', magicCount:[1,4] },
      '11-16':{ cp:0,       sp:0,       ep:0,       gp:[4,24],  pp:[5,30],  cpMult:1,   spMult:1,   gpMult:1000, gemChance:60, gemTier:'500',  artChance:50, artTier:'750',  magicChance:50, magicTable:'E', magicCount:[1,4], ppMult:100 },
      '17+':  { cp:0,       sp:0,       ep:0,       gp:[12,72], pp:[8,48],  cpMult:1,   spMult:1,   gpMult:1000, gemChance:70, gemTier:'1000', artChance:60, artTier:'2500', magicChance:70, magicTable:'I', magicCount:[1,4], ppMult:1000 }
    }
  }
};
